default:
  image: docker:dind
  services:
    - docker:dind
  before_script:
    - docker info

stages:
  - build

build-image:
  stage: build
  tags:
    - shiba
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker buildx create --name builder --bootstrap --use
    - docker compose version
    - docker compose build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --push
    - docker buildx rm builder
