default:
  image: docker:dind
  services:
    - docker:dind
  before_script:
    - docker info

stages:
  - build

build-image:
  stage: build
  tags:
    - shiba
  except:
    changes:
      - "**/*.md"
      - .gitlab-ci.yml
      - LICENSE
    variables:
      - '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - apk add --update --no-cache git
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker buildx create --name builder --bootstrap --use
    - docker compose version
    - echo "GIT_SHA=$(git rev-parse --short HEAD)" >> ./.env
    - docker compose build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --push
    - docker buildx rm builder
