default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info

stages:
  - build

build-image:
  stage: build
  tags:
    - shiba
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
  script:
    - apk add --update --no-cache git
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker login -u $GITLAB_USER -p $GITLAB_TOKEN registry.gitlab.com
    - docker context create builder-context
    - docker buildx create --name builder --driver docker-container --bootstrap --use builder-context
    - docker compose version
    - echo "GIT_SHA=$(git rev-parse --short HEAD)" >> ./.env
    - docker compose build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --push
    - docker buildx rm builder
