
services:
  base-alpine:
    build: 
      context: ./
      dockerfile: ./base/alpine.dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      tags:
        - wolfyuan/dolphin:base-alpine
        - wolfyuan/dolphin:base-alpine-${GIT_SHA}
        - registry.gitlab.com/wolf-yuan/dolphin:base-alpine
        - registry.gitlab.com/wolf-yuan/dolphin:base-alpine-${GIT_SHA}
  base-ubuntu:
    build:
      context: ./
      dockerfile: ./base/ubuntu.dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      tags:
        - wolfyuan/dolphin:base-ubuntu
        - wolfyuan/dolphin:base-ubuntu-${GIT_SHA}
        - wolfyuan/dolphin:base
        - registry.gitlab.com/wolf-yuan/dolphin:base-ubuntu
        - registry.gitlab.com/wolf-yuan/dolphin:base

  node-alpine:
    build:
      context: ./
      dockerfile: ./nodejs/alpine.dockerfile
      platforms:
        - linux/amd64
      tags:
        - wolfyuan/dolphin:node-alpine
        - wolfyuan/dolphin:node-alpine-${GIT_SHA}
        - registry.gitlab.com/wolf-yuan/dolphin:node-alpine
    depends_on:
      - base-alpine
  node-ubuntu:
    build:
      context: ./
      dockerfile: ./nodejs/ubuntu.dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      tags:
        - wolfyuan/dolphin:node-ubuntu
        - wolfyuan/dolphin:node-ubuntu-${GIT_SHA}
        - wolfyuan/dolphin:node
        - registry.gitlab.com/wolf-yuan/dolphin:node-ubuntu
        - registry.gitlab.com/wolf-yuan/dolphin:node
    depends_on:
      - base-ubuntu

  python-alpine:
    build:
      context: ./
      dockerfile: ./python/alpine.dockerfile
      platforms:
        - linux/amd64
      tags:
        - wolfyuan/dolphin:python-alpine
        - wolfyuan/dolphin:python-alpine-${GIT_SHA}
        - registry.gitlab.com/wolf-yuan/dolphin:python-alpine
    depends_on:
      - base-alpine
  python-ubuntu:
    build:
      context: ./
      dockerfile: ./python/ubuntu.dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      tags:
        - wolfyuan/dolphin:python-ubuntu
        - wolfyuan/dolphin:python-ubuntu-${GIT_SHA}
        - wolfyuan/dolphin:python
        - registry.gitlab.com/wolf-yuan/dolphin:python-ubuntu
        - registry.gitlab.com/wolf-yuan/dolphin:python
    depends_on:
      - base-ubuntu