
services:
  base-alpine:
    build: 
      context: ./
      dockerfile: ./base/Dockerfile.alpine
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    image: wolfyuan/dolphin:base-alpine
  base-ubuntu:
    build:
      context: ./
      dockerfile: ./base/Dockerfile.ubuntu
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    image: wolfyuan/dolphin:base-ubuntu
  base:
    extends: base-alpine
    image: wolfyuan/dolphin:base
    depends_on:
      - base-alpine

  node-alpine:
    build:
      context: ./
      dockerfile: ./nodejs/Dockerfile.alpine
      platforms:
        - linux/amd64
    image: wolfyuan/dolphin:node-alpine
    depends_on:
      - base-alpine
  node-ubuntu:
    build:
      context: ./
      dockerfile: ./nodejs/Dockerfile.ubuntu
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    image: wolfyuan/dolphin:node-ubuntu
    depends_on:
      - base-ubuntu
  node:
    extends: node-alpine
    image: wolfyuan/dolphin:node
    depends_on:
      - node-alpine
