
services:
  base-alpine:
    build: 
      context: ./
      dockerfile: ./base/alpine.dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    image: wolfyuan/dolphin:base-alpine
  base-ubuntu:
    build:
      context: ./
      dockerfile: ./base/ubuntu.dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    image: wolfyuan/dolphin:base-ubuntu
  base-alpine-commit:
    extends: base-alpine
    image: wolfyuan/dolphin:base-alpine-${GIT_SHA}
    depends_on:
      - base-alpine
  base-ubuntu-commit:
    extends: base-ubuntu
    image: wolfyuan/dolphin:base-ubuntu-${GIT_SHA}
    depends_on:
      - base-ubuntu

  base:
    extends: base-ubuntu
    image: wolfyuan/dolphin:base
    depends_on:
      - base-ubuntu

  node-alpine:
    build:
      context: ./
      dockerfile: ./nodejs/alpine.dockerfile
      platforms:
        - linux/amd64
    image: wolfyuan/dolphin:node-alpine
    depends_on:
      - base-alpine
  node-ubuntu:
    build:
      context: ./
      dockerfile: ./nodejs/ubuntu.dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    image: wolfyuan/dolphin:node-ubuntu
    depends_on:
      - base-ubuntu
  node-alpine-commit:
    extends: node-ubuntu
    image: wolfyuan/dolphin:node-alpine-${GIT_SHA}
    depends_on:
      - node-alpine
  node-ubuntu-commit:
    extends: node-ubuntu
    image: wolfyuan/dolphin:node-ubuntu-${GIT_SHA}
    depends_on:
      - node-ubuntu

  node:
    extends: node-ubuntu
    image: wolfyuan/dolphin:node
    depends_on:
      - node-ubuntu
