services:
  base-alpine:
    build: 
      context: ./
      dockerfile: ./base/Dockerfile.alpine
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      tags:
        - wolfyuan/dolphin:base-alpine
        - wolfyuan/dolphin:base
  base-ubuntu:
    build:
      context: ./
      dockerfile: ./base/Dockerfile.ubuntu
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      tags:
        - wolfyuan/dolphin:base-ubuntu

  node-alpine:
    build:
      context: ./
      dockerfile: ./nodejs/Dockerfile.alpine
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      tags:
        - wolfyuan/dolphin:node-alpine
        - wolfyuan/dolphin:node
    depends_on:
      - base-alpine
  node-ubuntu:
    build:
      context: ./
      dockerfile: ./nodejs/Dockerfile.ubuntu
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
      tags:
        - wolfyuan/dolphin:node-ubuntu
    depends_on:
      - base-ubuntu
