version: "3"

x-base-alpine: &default-base-alpine
  build: 
    context: ./
    dockerfile: ./base/alpine.dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
  image: wolfyuan/dolphin:base-alpine
x-base-ubuntu: &default-base-ubuntu
  build:
    context: ./
    dockerfile: ./base/ubuntu.dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
  image: wolfyuan/dolphin:base-ubuntu
x-node-alpine: &default-node-alpine
  build:
    context: ./
    dockerfile: ./nodejs/alpine.dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
  image: wolfyuan/dolphin:node-alpine
  depends_on:
    - base-alpine
x-node-ubuntu: &default-node-ubuntu
  build:
    context: ./
    dockerfile: ./nodejs/ubuntu.dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
  image: wolfyuan/dolphin:node-ubuntu
  depends_on:
    - base-ubuntu
x-python-alpine: &default-python-alpine
  build:
    context: ./
    dockerfile: ./python/alpine.dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
  image: wolfyuan/dolphin:python-alpine
  depends_on:
    - base-alpine
x-python-ubuntu: &default-python-ubuntu
  build:
    context: ./
    dockerfile: ./python/ubuntu.dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
  depends_on:
    - base-ubuntu
   
services:
  # Base images
  ## Alpine base
  base-alpine:
    << : *default-base-alpine

  base-alpine-git:
    << : *default-base-alpine
    image: wolfyuan/dolphin:base-alpine-${GIT_SHA}
    depends_on:
      - base-alpine

  base-alpine-gitlab:
    << : *default-base-alpine
    image: registry.gitlab.com/wolf-yuan/dolphin:base-alpine
    depends_on:
      - base-alpine

  ## Ubuntu base
    
  base:
    << : *default-base-ubuntu
    image: wolfyuan/dolphin:base

  base-gitlab:
    << : *default-base-ubuntu
    image: registry.gitlab.com/wolf-yuan/dolphin:base
    depends_on:
      - base

  base-ubuntu:
    << : *default-base-ubuntu
    depends_on:
      - base

  base-ubuntu-git:
    << : *default-base-ubuntu
    image: wolfyuan/dolphin:base-ubuntu-${GIT_SHA}
    depends_on:
      - base

  base-ubuntu-gitlab:
    << : *default-base-ubuntu
    image: registry.gitlab.com/wolf-yuan/dolphin:base-ubuntu
    depends_on:
      - base
  
  # Node images
  ## Alpine node

  node-alpine:
    << : *default-node-alpine
    image: wolfyuan/dolphin:node-alpine

  node-alpine-git:
    << : *default-node-alpine
    image: wolfyuan/dolphin:node-alpine-${GIT_SHA}
    depends_on:
      - node-alpine

  node-alpine-gitlab:
    << : *default-node-alpine
    image: registry.gitlab.com/wolf-yuan/dolphin:node-alpine
    depends_on:
      - node-alpine
    
  ## Ubuntu node

  node:
    << : *default-node-ubuntu
    image: wolfyuan/dolphin:node

  node-gitlab:
    << : *default-node-ubuntu
    image: registry.gitlab.com/wolf-yuan/dolphin:node
    depends_on:
      - node

  node-ubuntu:
    << : *default-node-ubuntu
    depends_on:
      - node

  node-ubuntu-git:
    << : *default-node-ubuntu
    image: wolfyuan/dolphin:node-ubuntu-${GIT_SHA}
    depends_on:
      - node

  node-ubuntu-gitlab:
    << : *default-node-ubuntu
    image: registry.gitlab.com/wolf-yuan/dolphin:node-ubuntu
    depends_on:
      - node
    
  # Python images
  ## Alpine python

  python-alpine:
    << : *default-python-alpine
    image: wolfyuan/dolphin:python-alpine
    
  python-alpine-git:
    << : *default-python-alpine
    image: wolfyuan/dolphin:python-alpine-${GIT_SHA}
    depends_on:
      - python-alpine

  python-alpine-gitlab:
    << : *default-python-alpine
    image: registry.gitlab.com/wolf-yuan/dolphin:python-alpine
    depends_on:
      - python-alpine
    
  ## Ubuntu python

  python:
    << : *default-python-ubuntu
    image: wolfyuan/dolphin:python

  python-gitlab:
    << : *default-python-ubuntu
    image: registry.gitlab.com/wolf-yuan/dolphin:python
    depends_on:
      - python

  python-ubuntu:
    << : *default-python-ubuntu
    depends_on:
      - python

  python-ubuntu-git:
    << : *default-python-ubuntu
    image: wolfyuan/dolphin:python-ubuntu-${GIT_SHA}
    depends_on:
      - python

  python-ubuntu-gitlab:
    << : *default-python-ubuntu
    image: registry.gitlab.com/wolf-yuan/dolphin:python-ubuntu
    depends_on:
      - python
