services:
  base:
    build: 
      context: ./
      dockerfile: ./base/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    image: wolfyuan/dolphin:base
  nodejs:
    build:
      context: ./
      dockerfile: ./nodejs/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    image: wolfyuan/dolphin:node
    depends_on:
      - base
