version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-docker-image:
    machine: true
    resource_class: wolf-yuan-6115/shiba
    steps:
      - checkout
      - docker/install-docker-tools
      - docker/install-docker-credential-helper
      - docker/configure-docker-credentials-store
      - run:
          name: Login to Docker Hub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
      - run:
          name: Setup builder
          command: docker buildx create --name builder --bootstrap --use
      - run:
          name: Check docker compose version
          command: docker-compose version
      - run:
          name: Build and push Docker image via compose
          command: docker-compose build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --push
      - docker/update-description:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
          image: wolfyuan/dolphin
          
        
workflows:
  build:
    jobs:
      - build-docker-image:
          name: "Build and push Docker image"
