version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
          docker_layer_caching: true
      - docker/install-docker-tools
      - run:
          name: Login to Docker Hub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
      - run:
          name: Setup builder
          command: docker buildx create --name builder --bootstrap --use
      - run:
          name: Check docker compose version
          command: docker compose version
      - run:
          name: Build Docker image via compose
          command: docker compose build
      - run:
          name: Push to Docker Hub
          command: docker compose push
        
workflows:
  build:
    jobs:
      - build
