version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-docker-image:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/install-docker-compose:
          version: v2.21.0
      - run:
          name: Login to Docker Hub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
      - run:
          name: Setup builder
          command: docker buildx create --name builder --bootstrap --use
      - run:
          name: Check docker compose version
          command: docker-compose version
      - run:
          name: Build and push Docker image via compose
          command: docker-compose build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --push
        
workflows:
  build:
    jobs:
      - build-docker-image:
          name: "Build and push Docker image"
