#!/usr/bin/with-contenv bash

echo "Welcome to dolphin container"

echo "
  ___      _      _    _      
 |   \ ___| |_ __| |_ (_)_ _  
 | |) / _ \ | '_ \ ' \| | ' \ 
 |___/\___/_| .__/_||_|_|_||_|
            |_|               
            
"