#!/usr/bin/with-contenv bash

if [[ ! -z "${SYSTEM_PACKAGES}" ]]; then
  echo "[+] Found SYSTEM_PACKAGES"
  
  OS=$(grep -E '^(ID)=' /etc/os-release)
  if [[ $OS == "ID=alpine" ]]; then
    install-command() {
      apk add --no-cache --update --virtual runtime-dependencies "$@"
    }
  elif [[ $OS == "ID=ubuntu" ]]; then
    pre-command() {
      apt-get update
    }
    install-command() {
      apt-get install -y "$@"
    }
    post-command() {
      apt-get clean
    }
  fi

  if [[ $(declare -f pre-command) ]]; then
    pre-command
  fi
  
  install-command $SYSTEM_PACKAGES

  if [[ $(declare -f post-command) ]]; then
    post-command
  fi
else
  echo "[-] No SYSTEM_PACKAGES found, skipping..."
fi