#!/usr/bin/with-contenv bash

export HOME="/home/dolphin"
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

cd /home/dolphin/space

echo "[+] Starting service"
SCRIPT_RAN=0

if [[ ! -z "${PYTHON_START_SCRIPT}" ]]; then
  SCRIPT_RAN=1
  echo "[+] Found PYTHON_START_SCRIPT"
  eval "${PYTHON_START_SCRIPT}"
fi

if [[ ! -z "${PYTHON_START_FILE}" ]]; then
  SCRIPT_RAN=1
  echo "[+] Found PYTHON_START_FILE"
  python ${PYTHON_START_FILE}
fi

if [[ "${SCRIPT_RAN}" == "1" ]]; then
  echo "[x] No start script found in PYTHON_START_SCRIPT or PYTHON_START_FILE"
  exit 1
fi
