#!/usr/bin/with-contenv bash

export HOME="/home/dolphin"
export NVM_DIR="$HOME/.nvm"
if [[ -d "$NVM_DIR" ]]; then
  echo "[+] nvm is already installed"
else
  echo "[+] Installing nvm"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi
